// Code generated by go-swagger; DO NOT EDIT.

package sql_web_handler

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/SzMark092/MS_Gyak/PSQL_Server/models"
)

// GetDataPointDescriptionTableOKCode is the HTTP code returned for type GetDataPointDescriptionTableOK
const GetDataPointDescriptionTableOKCode int = 200

/*GetDataPointDescriptionTableOK JSON object containing table information

swagger:response getDataPointDescriptionTableOK
*/
type GetDataPointDescriptionTableOK struct {

	/*
	  In: Body
	*/
	Payload []*models.DataPointDescription `json:"body,omitempty"`
}

// NewGetDataPointDescriptionTableOK creates GetDataPointDescriptionTableOK with default headers values
func NewGetDataPointDescriptionTableOK() *GetDataPointDescriptionTableOK {

	return &GetDataPointDescriptionTableOK{}
}

// WithPayload adds the payload to the get data point description table o k response
func (o *GetDataPointDescriptionTableOK) WithPayload(payload []*models.DataPointDescription) *GetDataPointDescriptionTableOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get data point description table o k response
func (o *GetDataPointDescriptionTableOK) SetPayload(payload []*models.DataPointDescription) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDataPointDescriptionTableOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.DataPointDescription, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetDataPointDescriptionTableNotFoundCode is the HTTP code returned for type GetDataPointDescriptionTableNotFound
const GetDataPointDescriptionTableNotFoundCode int = 404

/*GetDataPointDescriptionTableNotFound There is no data to send

swagger:response getDataPointDescriptionTableNotFound
*/
type GetDataPointDescriptionTableNotFound struct {
}

// NewGetDataPointDescriptionTableNotFound creates GetDataPointDescriptionTableNotFound with default headers values
func NewGetDataPointDescriptionTableNotFound() *GetDataPointDescriptionTableNotFound {

	return &GetDataPointDescriptionTableNotFound{}
}

// WriteResponse to the client
func (o *GetDataPointDescriptionTableNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
