// Code generated by go-swagger; DO NOT EDIT.

package sql_web_handler

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetHomePageOKCode is the HTTP code returned for type GetHomePageOK
const GetHomePageOKCode int = 200

/*GetHomePageOK Home page is ready.

swagger:response getHomePageOK
*/
type GetHomePageOK struct {
}

// NewGetHomePageOK creates GetHomePageOK with default headers values
func NewGetHomePageOK() *GetHomePageOK {

	return &GetHomePageOK{}
}

// WriteResponse to the client
func (o *GetHomePageOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
