// Code generated by go-swagger; DO NOT EDIT.

package sql_web_handler

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetTableHandlerFunc turns a function with the right signature into a get table handler
type GetTableHandlerFunc func(GetTableParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetTableHandlerFunc) Handle(params GetTableParams) middleware.Responder {
	return fn(params)
}

// GetTableHandler interface for that can handle valid get table params
type GetTableHandler interface {
	Handle(GetTableParams) middleware.Responder
}

// NewGetTable creates a new http.Handler for the get table operation
func NewGetTable(ctx *middleware.Context, handler GetTableHandler) *GetTable {
	return &GetTable{Context: ctx, Handler: handler}
}

/*GetTable swagger:route GET /GetTable SQLWebHandler getTable

Get the specified table from the SQL server.

*/
type GetTable struct {
	Context *middleware.Context
	Handler GetTableHandler
}

func (o *GetTable) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetTableParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
