// Code generated by go-swagger; DO NOT EDIT.

package sql_web_handler

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/SzMark092/MS_Gyak/PSQL_Server/models"
)

// GetDataPointTableOKCode is the HTTP code returned for type GetDataPointTableOK
const GetDataPointTableOKCode int = 200

/*GetDataPointTableOK JSON object containing table information

swagger:response getDataPointTableOK
*/
type GetDataPointTableOK struct {

	/*
	  In: Body
	*/
	Payload []*models.DataPoint `json:"body,omitempty"`
}

// NewGetDataPointTableOK creates GetDataPointTableOK with default headers values
func NewGetDataPointTableOK() *GetDataPointTableOK {

	return &GetDataPointTableOK{}
}

// WithPayload adds the payload to the get data point table o k response
func (o *GetDataPointTableOK) WithPayload(payload []*models.DataPoint) *GetDataPointTableOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get data point table o k response
func (o *GetDataPointTableOK) SetPayload(payload []*models.DataPoint) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDataPointTableOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.DataPoint, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetDataPointTableNotFoundCode is the HTTP code returned for type GetDataPointTableNotFound
const GetDataPointTableNotFoundCode int = 404

/*GetDataPointTableNotFound There is no data to send

swagger:response getDataPointTableNotFound
*/
type GetDataPointTableNotFound struct {
}

// NewGetDataPointTableNotFound creates GetDataPointTableNotFound with default headers values
func NewGetDataPointTableNotFound() *GetDataPointTableNotFound {

	return &GetDataPointTableNotFound{}
}

// WriteResponse to the client
func (o *GetDataPointTableNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
