// Code generated by go-swagger; DO NOT EDIT.

package home_page

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetHomePageHandlerFunc turns a function with the right signature into a get home page handler
type GetHomePageHandlerFunc func(GetHomePageParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetHomePageHandlerFunc) Handle(params GetHomePageParams) middleware.Responder {
	return fn(params)
}

// GetHomePageHandler interface for that can handle valid get home page params
type GetHomePageHandler interface {
	Handle(GetHomePageParams) middleware.Responder
}

// NewGetHomePage creates a new http.Handler for the get home page operation
func NewGetHomePage(ctx *middleware.Context, handler GetHomePageHandler) *GetHomePage {
	return &GetHomePage{Context: ctx, Handler: handler}
}

/*GetHomePage swagger:route GET /HomePage HomePage getHomePage

Get the home page of REST API to send requests to the server.

*/
type GetHomePage struct {
	Context *middleware.Context
	Handler GetHomePageHandler
}

func (o *GetHomePage) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetHomePageParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
