package main

import (
	"github.com/SzMark092/MS_Gyak/PSQL_Server/restapi"
	"github.com/SzMark092/MS_Gyak/internal/web"

	"log"
	"net/http"
)

// This file was generated by the swagger tool.
// Make sure not to overwrite this file after you generated it because all your edits would be lost!

func main() {
	// Initiate business logic implementers.
	// This is the main function, so here the implementers' dependencies can be
	// injected, such as database, parameters from environment variables, or different
	// clients for different APIs.

	p, err1 := web.New()

	// Initiate the http handler, with the objects that are implementing the business logic.
	h, err := restapi.Handler(restapi.Config{
		SQLWebHandlerAPI: p,

		Logger: log.Printf,
	})
	if err != nil {
		log.Fatal(err)
	}

	log.Println("Starting to serve, access server on http://localhost:8080")

	// Run the standard http server
	log.Fatal(http.ListenAndServe(":8080", h))

}
