/*
 * Homework server
 * This is a simple server for my homework. It can make request towards a PSQL database, and get full tables of data from it.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: szmgepesz@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.12
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.HomeworkServer) {
      root.HomeworkServer = {};
    }
    root.HomeworkServer.Module = factory(root.HomeworkServer.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The Module model module.
   * @module model/Module
   * @version 2.0.0
   */

  /**
   * Constructs a new <code>Module</code>.
   * @alias module:model/Module
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>Module</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Module} obj Optional instance to populate.
   * @return {module:model/Module} The populated <code>Module</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('ID'))
        obj.ID = ApiClient.convertToType(data['ID'], 'Number');
      if (data.hasOwnProperty('Name'))
        obj.name = ApiClient.convertToType(data['Name'], 'String');
      if (data.hasOwnProperty('Title'))
        obj.title = ApiClient.convertToType(data['Title'], 'String');
      if (data.hasOwnProperty('Max'))
        obj.max = ApiClient.convertToType(data['Max'], 'Number');
    }
    return obj;
  }

  /**
   * @member {Number} ID
   */
  exports.prototype.ID = undefined;

  /**
   * @member {String} name
   */
  exports.prototype.name = undefined;

  /**
   * @member {String} title
   */
  exports.prototype.title = undefined;

  /**
   * @member {Number} max
   */
  exports.prototype.max = undefined;

  return exports;

}));
