// Code generated by go-swagger; DO NOT EDIT.

package get_table

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetTableOKCode is the HTTP code returned for type GetTableOK
const GetTableOKCode int = 200

/*GetTableOK JSON object containing table information

swagger:response getTableOK
*/
type GetTableOK struct {
}

// NewGetTableOK creates GetTableOK with default headers values
func NewGetTableOK() *GetTableOK {

	return &GetTableOK{}
}

// WriteResponse to the client
func (o *GetTableOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// GetTableMethodNotAllowedCode is the HTTP code returned for type GetTableMethodNotAllowed
const GetTableMethodNotAllowedCode int = 405

/*GetTableMethodNotAllowed Invalid input

swagger:response getTableMethodNotAllowed
*/
type GetTableMethodNotAllowed struct {
}

// NewGetTableMethodNotAllowed creates GetTableMethodNotAllowed with default headers values
func NewGetTableMethodNotAllowed() *GetTableMethodNotAllowed {

	return &GetTableMethodNotAllowed{}
}

// WriteResponse to the client
func (o *GetTableMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}
