// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Homework server
This is a simple server for my homework. It can make request towards a PSQL database, and get full tables of data from it.


    Schemes:
      http
      https
    Host: petstore.swagger.io
    BasePath: /
    Version: 2.0.0
    Contact: <szmgepesz@gmail.com>

    Consumes:
    - application/json

    Produces:
    - application/json
    - text/html

swagger:meta
*/
package restapi
