// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "This is a simple server for my homework. It can make request towards a PSQL database, and get full tables of data from it.",
    "title": "Homework server",
    "contact": {
      "email": "szmgepesz@gmail.com"
    },
    "version": "2.0.0"
  },
  "host": "petstore.swagger.io",
  "basePath": "/",
  "paths": {
    "/CreateTable": {
      "post": {
        "tags": [
          "SQLWebHandler"
        ],
        "summary": "Create a table with the given code.",
        "operationId": "CreateTable",
        "parameters": [
          {
            "type": "integer",
            "description": "Type of the table that have to be created.",
            "name": "TableType",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "405": {
            "description": "Invalid input"
          }
        }
      }
    },
    "/GetTable": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "SQLWebHandler"
        ],
        "summary": "Get the specified table from the SQL server.",
        "operationId": "GetTable",
        "parameters": [
          {
            "type": "integer",
            "description": "Type of the table that have to be created.",
            "name": "TableType",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "JSON object containing table information"
          },
          "405": {
            "description": "Invalid input"
          }
        }
      }
    },
    "/HomePage": {
      "get": {
        "produces": [
          "text/html"
        ],
        "tags": [
          "SQLWebHandler"
        ],
        "summary": "Get the home page of REST API to send requests to the server.",
        "operationId": "getHomePage",
        "responses": {
          "200": {
            "description": "Home page is ready."
          }
        }
      }
    }
  },
  "definitions": {
    "DataPoint": {
      "type": "object",
      "properties": {
        "DataPointDescription": {
          "type": "object",
          "format": "$ref:\"#/definitions/DataPointDescription\""
        },
        "ID": {
          "type": "integer",
          "format": "int64"
        },
        "Module": {
          "type": "object",
          "format": "$ref:\"#/definitions/Module\""
        },
        "Timestamp": {
          "type": "string",
          "format": "date-time"
        },
        "Value": {
          "type": "number",
          "format": "float"
        }
      }
    },
    "DataPointDescription": {
      "type": "object",
      "properties": {
        "ID": {
          "type": "integer",
          "format": "int64"
        },
        "Max": {
          "type": "integer",
          "format": "int64"
        },
        "Min": {
          "type": "integer",
          "format": "int64"
        },
        "Name": {
          "type": "string"
        },
        "Title": {
          "type": "string"
        }
      }
    },
    "Module": {
      "type": "object",
      "properties": {
        "ID": {
          "type": "integer",
          "format": "int64"
        },
        "Max": {
          "type": "integer",
          "format": "int64"
        },
        "Name": {
          "type": "string"
        },
        "Title": {
          "type": "string"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "This is a simple server for my homework. It can make request towards a PSQL database, and get full tables of data from it.",
    "title": "Homework server",
    "contact": {
      "email": "szmgepesz@gmail.com"
    },
    "version": "2.0.0"
  },
  "host": "petstore.swagger.io",
  "basePath": "/",
  "paths": {
    "/CreateTable": {
      "post": {
        "tags": [
          "SQLWebHandler"
        ],
        "summary": "Create a table with the given code.",
        "operationId": "CreateTable",
        "parameters": [
          {
            "type": "integer",
            "description": "Type of the table that have to be created.",
            "name": "TableType",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "405": {
            "description": "Invalid input"
          }
        }
      }
    },
    "/GetTable": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "SQLWebHandler"
        ],
        "summary": "Get the specified table from the SQL server.",
        "operationId": "GetTable",
        "parameters": [
          {
            "type": "integer",
            "description": "Type of the table that have to be created.",
            "name": "TableType",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "JSON object containing table information"
          },
          "405": {
            "description": "Invalid input"
          }
        }
      }
    },
    "/HomePage": {
      "get": {
        "produces": [
          "text/html"
        ],
        "tags": [
          "SQLWebHandler"
        ],
        "summary": "Get the home page of REST API to send requests to the server.",
        "operationId": "getHomePage",
        "responses": {
          "200": {
            "description": "Home page is ready."
          }
        }
      }
    }
  },
  "definitions": {
    "DataPoint": {
      "type": "object",
      "properties": {
        "DataPointDescription": {
          "type": "object",
          "format": "$ref:\"#/definitions/DataPointDescription\""
        },
        "ID": {
          "type": "integer",
          "format": "int64"
        },
        "Module": {
          "type": "object",
          "format": "$ref:\"#/definitions/Module\""
        },
        "Timestamp": {
          "type": "string",
          "format": "date-time"
        },
        "Value": {
          "type": "number",
          "format": "float"
        }
      }
    },
    "DataPointDescription": {
      "type": "object",
      "properties": {
        "ID": {
          "type": "integer",
          "format": "int64"
        },
        "Max": {
          "type": "integer",
          "format": "int64"
        },
        "Min": {
          "type": "integer",
          "format": "int64"
        },
        "Name": {
          "type": "string"
        },
        "Title": {
          "type": "string"
        }
      }
    },
    "Module": {
      "type": "object",
      "properties": {
        "ID": {
          "type": "integer",
          "format": "int64"
        },
        "Max": {
          "type": "integer",
          "format": "int64"
        },
        "Name": {
          "type": "string"
        },
        "Title": {
          "type": "string"
        }
      }
    }
  }
}`))
}
